### ISSUE TITLE
Unable to run tests locally (BadArguments error): add a CONTRIBUTING.md file?

### ISSUE THREAD

**Issue by Delgan** [notifiers/notifiers#103]
Hi again.

I wanted to fork `notifiers` and run tests on my computer.

```
$ git clone https://github.com/Delgan/notifiers
$ cd notifiers/
$ git checkout master
$ python3.6 -m virtualenv env
$ source env/bin/activate
$ pip install -e .
$ pip install -r dev-requirements.txt
$ pytest tests
============================= test session starts =============================
platform linux -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /mnt/c/Users/adrie/Desktop/notifiers, inifile: setup.cfg
plugins: cov-2.5.1
collected 197 items

tests/test_cli.py ..............
tests/test_core.py .............................
tests/test_logger.py .......
tests/providers/test_gitter.py .....FF....FF.FF
tests/providers/test_gmail.py ...F...
tests/providers/test_hipchat.py ............
tests/providers/test_join.py ....s.....s
tests/providers/test_mailgun.py ......FF.
tests/providers/test_pagerduty.py ......FF
tests/providers/test_popcornnotify.py ....F.
tests/providers/test_pushbullet.py ...FFFss
tests/providers/test_pushover.py ....FFFF.F..F..F.F.F
tests/providers/test_simplepush.py ...F
tests/providers/test_slack.py .FF
tests/providers/test_smtp.py ......F
tests/providers/test_statuspage.py ........FFFF..
tests/providers/test_telegram.py .....FFF..F.F
tests/providers/test_twilio.py .F
tests/providers/test_zulip.py ...FF..
                                                                   

============== 42 failed, 151 passed, 4 skipped in 17.40 seconds ===============
```

Many of the tests are failing with an error like:

    notifiers.exceptions.BadArguments: Error with sent data: 'user' is a required property

What am I doing wrong?

**Comment by liiight** [comment]
Yeah, adding a CONTRIBUTING.MD is in my backlog. 
Some of tests are marked as online (`@pytest.mark.online`), meaning they actually hit the relevant norifiers' APIs. The keys to these requests is stored via the travis.yml file (and some configured directly under my travis account, need to consolidate those), which is accesible only to me and only when running on travis.

To skip these tests run: `pytest -m "not online"`

**Comment by Delgan** [comment]
That makes sense, thanks for the explanation!

The `pytest` command works fine (except for two Gitter tests failing because of a maintenance at the time of writing these lines). 👍

**Comment by liiight** [comment]
Solved with https://github.com/notifiers/notifiers/commit/bc301f0d1f88c6249f6f679a9842eb33a1247eeb
