### ISSUE TITLE
Provider 'email' does not accept multiple mail addresses

### ISSUE THREAD

**Issue by Magnati** [notifiers/notifiers#134]
According to the specs [email.prepare_data](https://github.com/notifiers/notifiers/blob/develop/notifiers/providers/email.py) of notifiers the parameter `to` of provider `email` should accept a list of addresses. 
It accepts the list, but does not sent mails to all addresses.

Neither is the case when doing the job of [list_to_commas](https://github.com/notifiers/notifiers/blob/develop/notifiers/utils/schema/helpers.py)
providing one string with `','join()` explicetely

In both cases only the first mail-address is receiving a mail

Here an example code.

```python
import pathlib
import notifiers

def test_notify(mail_list):
    p = notifiers.get_notifier("email")

    # fill in your credentials
    my_user = "my_user"
    my_port = -1
    my_host = "my_host"

    status = p.notify(
        to=mail_list,
        username=my_user,
        message="Testmessage",
        subject="Test",
        ssl=True,
        port=my_port,
        host=my_host,
        html=True,
    )
    print(status)

if __name__ == "__main__":
    mail_list = ['my.first@foo.com', 'my.second@bar.com']
    test_notify(mail_list)
    test_notify(",".join(mail_list))

```

**Comment by Magnati** [comment]
Where do I find the issue template?

**Comment by liiight** [comment]
Thanks for opening this issue. I've been meaning to refactor the email provider, this is a good opportunity.
