### ISSUE TITLE
Attachment in mail changes filename when it resides in different path from source

### ISSUE THREAD

**Issue by kdasoulas** [notifiers/notifiers#276]
Hello,

I have noticed an issue when you send an email (SMTP) with attachments and the files to be attached are not in the same directory where the python files are.

For example, if I want to attach an Excel file which is (in relation to my *.py files) in directory 'Reports/myreport.xlsx', the email is being sent correctly but the name of the Excel attached is renamed to 'Reportsmyreport.xlsx'.

To fix this issue in the providers directory in file email.py, we can change line 125 from:

`part.add_header("Content-Disposition", "attachment", filename=attachment)`

to:

`part.add_header("Content-Disposition", "attachment", filename=attachment
  [attachment.rfind(re.findall(r'(/|\\)', attachment)[-1]) + 1 
   if len(re.findall(r'(/|\\)', attachment)) > 0 else 0:])`

in order to take into account also possible Windows paths. Of course we also need to import re module.

Moreover, in the same file (email.py) there is a typo in line 73 ("parse" instead of "parsed").

Thank you.

**Comment by liiight** [comment]
Thanks for reporting this!

I actually refactored this area in https://github.com/notifiers/notifiers/pull/267.

I believe this would address this issue as well.

**Comment by liiight** [comment]
Fixed in 1.2.0
