### ISSUE TITLE
Dependencies of notifiers are fixed.

### ISSUE THREAD

**Issue by tobiasraabe** [notifiers/notifiers#282]
First, thanks for the package. It is very intuitive and works like a charm! 👍 

**Describe the bug**

If I install notifiers, it checks whether the dependencies in [requirements.txt](https://github.com/notifiers/notifiers/blob/master/requirements.txt) are met. Unfortunately, I run into the same issue as #191 which I cannot circumvent within tox with the stated pip command.

Is it possible to relax the dependencies? In the requirement file it is stated that the dependency comes via ``requests``, but then you could let ``requests`` handle it and just refer to a version of ``requests`` which works for you (better a certain range). Also, even ``requests`` is not that strict regarding ``certifi`` (see [here](https://github.com/kennethreitz/requests/blob/aeda65bbe57ac5edbcc2d80db85d010befb7d419/setup.py#L48)).

Or is there another reason for you to pin ``certifiy``?

**Additional context**
Python version: 3.6, 3.7
OS: Windows, Linux, MacOS

**Comment by liiight** [comment]
Thanks for your issue. I actually solved this via #209 which isn't merged to master yet, but it's in the next release.
