### ISSUE TITLE
Cannot install notifiers in a conda activated Python environment (Windows & Ubuntu)

### ISSUE THREAD

**Issue by PyDataBlog** [notifiers/notifiers#284]
**Describe the bug**
Notifiers fails to install in a conda environment due to an issue with this error raised:

```
Installing collected packages: idna, urllib3, rfc3987, certifi, click, notifiers
  Found existing installation: idna 2.8
    Uninstalling idna-2.8:
      Successfully uninstalled idna-2.8
  Found existing installation: urllib3 1.24.1
    Uninstalling urllib3-1.24.1:
      Successfully uninstalled urllib3-1.24.1
  Found existing installation: certifi 2019.3.9
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

```

**To Reproduce**
run ` pip install notifiers` in a conda activated Python environment.

**Expected behaviour**
Expected notifiers to install without any issue

**Additional context**
Python version: 3.7.3 & 3.6.7
OS: Windows 10 & Ubuntu 18.04

**Comment by liiight** [comment]
I have no experience with Conda actually, but I'll try to take a peek, Thanks for reporting!

**Comment by firejava** [comment]
windows 10, Python 3.7.4, conda 4.7.12

pip install notifiers 

install worked fine for me.

**Comment by PyDataBlog** [comment]
@firejava I'll give it a go again and report.

**Comment by PyDataBlog** [comment]
Update: It seems to install fine now with version 1.2.1

**Comment by liiight** [comment]
Cool, thanks for updating!
