### ISSUE TITLE
Add installation via brew

### ISSUE THREAD

**Issue by liiight** [notifiers/notifiers#78]

**Comment by exequiel09** [comment]
I'd like to take this on. :)

**Comment by exequiel09** [comment]
If I will take this on, basically you want a it to be installed in homebrew in and update the REAME? Please advise. Thanks.

**Comment by liiight** [comment]
I was thinking just `brew install notifiers` if that's available.

Thanks!

**Comment by exequiel09** [comment]
@liiight  #308 needs to be resolved first before the solution to this issue can proceed.

**Comment by exequiel09** [comment]
@liiight I think you'll need to release a 1.2.1 version that includes the `README.MD` in the tarball.
